/**
 * ============================================================
 *  Contact controller — the ONE submission endpoint used by all
 *  three contact forms (Hero, Home contact section, Contact page):
 *
 *      POST /api/contact
 *
 *  Backend validation is mandatory — frontend validation is never
 *  trusted:
 *   * every string field is trimmed & sanitized (shared
 *     middleware/validate helpers, same as leads/meetings),
 *   * email is lower-cased and format-checked,
 *   * all required fields are present,
 *   * agreeToContact must be exactly true,
 *   * source must be one of hero | home-contact | contact-page,
 *   * the row is INSERTED into MySQL with a prepared statement,
 *   * timestamps are generated by MySQL, never by the client,
 *   * no SQL error, stack trace or credential ever reaches the client.
 * ============================================================
 */
const { sanitize, isEmail } = require("../middleware/validate");
const contacts = require("../models/contactModel");

/* Same options the frontend dropdowns submit — stored verbatim. */
const MAX_LENGTHS = {
  firstName: 80,
  lastName: 80,
  email: 190,
  companyName: 190,
  helpWith: 190,
  country: 100,
  message: 5000,
  hearAbout: 120,
  source: 40,
};

const REQUIRED_LABELS = {
  firstName: "First name",
  lastName: "Last name",
  email: "Email",
  companyName: "Company name",
  helpWith: "What can we help with",
  country: "Country",
  message: "Message",
  hearAbout: "How did you hear about us",
};

/* Exact response bodies required by the API contract. */
const MESSAGES = {
  success: "Your message has been submitted successfully.",
  validation: "Please complete all required fields.",
  server: "Something went wrong. Please try again.",
};

function badRequest(res, errors) {
  return res.status(400).json({
    success: false,
    message: MESSAGES.validation,
    errors,
  });
}

function serverError(res, err) {
  // Full detail in the server log only — never in the response.
  console.error("[contact] submission failed:", require("../config/mysql").safeError(err));
  return res.status(500).json({ success: false, message: MESSAGES.server });
}

/* ---------------- validation + normalization ---------------- */

function normalize(body) {
  const raw = body && typeof body === "object" ? body : {};

  const data = {
    firstName: sanitize(raw.firstName, MAX_LENGTHS.firstName),
    lastName: sanitize(raw.lastName, MAX_LENGTHS.lastName),
    email: sanitize(raw.email, MAX_LENGTHS.email).toLowerCase(),
    companyName: sanitize(raw.companyName, MAX_LENGTHS.companyName),
    helpWith: sanitize(raw.helpWith, MAX_LENGTHS.helpWith),
    country: sanitize(raw.country, MAX_LENGTHS.country),
    message: sanitize(raw.message, MAX_LENGTHS.message),
    // Stored exactly as the frontend dropdown submits it (LinkedIn, Google
    // Search, X / Twitter, Referral / Word of Mouth, …).
    hearAbout: sanitize(raw.hearAbout, MAX_LENGTHS.hearAbout),
    source: sanitize(raw.source, MAX_LENGTHS.source).toLowerCase(),
    // The checkbox is a real boolean in the forms; accept the string form too
    // so URL-encoded submitters are not rejected.
    agreeToContact: raw.agreeToContact === true || raw.agreeToContact === "true",
  };

  const errors = [];

  Object.keys(REQUIRED_LABELS).forEach((field) => {
    if (!data[field]) errors.push(`${REQUIRED_LABELS[field]} is required`);
  });

  if (data.email && !isEmail(data.email)) {
    errors.push("Please provide a valid email address");
  }

  if (!data.agreeToContact) {
    errors.push("You must agree to be contacted");
  }

  if (!contacts.ALLOWED_SOURCES.includes(data.source)) {
    errors.push("Invalid source");
  }

  return { data, errors };
}

/* ---------------- POST /api/contact ---------------- */

exports.createContact = async (req, res) => {
  const body = (req.body && typeof req.body === "object" ? req.body : {}) || {};

  // Honeypot — same spam guard the other public forms use. A real visitor
  // never fills this hidden field, so a filled one is reported as a normal
  // validation failure (no hint that it was a bot trap).
  if (sanitize(body.website, 60)) {
    return badRequest(res, ["Please complete all required fields."]);
  }

  const { data, errors } = normalize(body);
  if (errors.length) return badRequest(res, errors);

  try {
    const record = await contacts.insertContact(data);

    console.log(
      `[contact] stored id=${record.id} source=${data.source} country=${data.country}`
    );

    return res.status(201).json({
      success: true,
      message: MESSAGES.success,
      data: { id: record.id },
    });
  } catch (err) {
    return serverError(res, err);
  }
};

exports.MESSAGES = MESSAGES;
exports.normalize = normalize;