-- ============================================================
--  001 — contacts
--  Every contact-form submission (Hero, Home contact section,
--  Contact page) is stored here, in MySQL.
--
--  Applied with:  npm run migrate        (idempotent)
--  Also applied automatically when the server boots.
--
--  Design notes (future Admin Panel):
--   * email is intentionally NOT unique → the same person or
--     company may send several legitimate enquiries.
--   * `source` records where the enquiry came from:
--       hero | home-contact | contact-page
--   * `status` exists from day one (same convention as every
--     other record in this project, which is created with
--     status = 'new') so the panel can later add workflows.
--   * indexes cover the filters/searches the panel needs:
--     source, country, helpWith, hearAbout, status,
--     email, companyName, createdAt.
--   * createdAt / updatedAt are generated by MySQL itself —
--     the frontend never sends timestamps.
-- ============================================================

CREATE TABLE IF NOT EXISTS `contacts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(80) NOT NULL,
  `lastName` VARCHAR(80) NOT NULL,
  `email` VARCHAR(190) NOT NULL,
  `companyName` VARCHAR(190) NOT NULL,
  `helpWith` VARCHAR(190) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `message` TEXT NOT NULL,
  `hearAbout` VARCHAR(120) NOT NULL,
  `agreeToContact` TINYINT(1) NOT NULL DEFAULT 0,
  `source` VARCHAR(40) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'new',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_contacts_source` (`source`),
  KEY `idx_contacts_country` (`country`),
  KEY `idx_contacts_help_with` (`helpWith`),
  KEY `idx_contacts_hear_about` (`hearAbout`),
  KEY `idx_contacts_status` (`status`),
  KEY `idx_contacts_email` (`email`),
  KEY `idx_contacts_company_name` (`companyName`),
  KEY `idx_contacts_created_at` (`createdAt`),
  KEY `idx_contacts_source_created_at` (`source`, `createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;