-- ============================================================
--  002 — subscribers
--  Newsletter subscription form (frontend:
--  components/SubscribeSection.jsx) → POST /api/subscribe.
--
--  Applied with:  npm run migrate        (idempotent)
--  Also applied automatically when the server boots.
--
--  Design notes:
--   * `email` is UNIQUE — one row per subscriber, so a repeat
--     submission is reported as "already subscribed" (HTTP 409)
--     instead of silently creating a second record.
--   * `agreeToSubscribe` stores the consent flag (never trust the
--     client to enforce it — the API validates it too).
--   * `status` supports a future unsubscribe flow
--     ('active' | 'unsubscribed') without a schema change.
--   * createdAt / updatedAt are generated by MySQL itself —
--     the frontend never sends timestamps.
-- ============================================================

CREATE TABLE IF NOT EXISTS `subscribers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(190) NOT NULL,
  `agreeToSubscribe` TINYINT(1) NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_subscribers_email` (`email`),
  KEY `idx_subscribers_status` (`status`),
  KEY `idx_subscribers_created_at` (`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;