-- ============================================================
--  003 — news
--  Global News CMS articles (frontend: pages/News.jsx,
--  pages/NewsDetails.jsx, pages/AdminNews.jsx) → /api/news* and
--  /api/admin/news*.
--
--  Applied with:  npm run migrate        (idempotent)
--  Also applied automatically when the server boots.
--
--  WHY THIS TABLE EXISTS
--  News used to be stored ONLY in `backend/data/news.json`. Render
--  wipes its local filesystem on every restart / redeploy (and when
--  a free instance spins down), so every published article vanished.
--  MySQL is the durable store the project already uses for contacts
--  and subscribers; the JSON file is now only a local read mirror
--  (see models/newsModel.js).
--
--  Design notes:
--   * `id` is the id generated by the app (text, not AUTO_INCREMENT)
--     so the pre-existing JSON documents keep their identity and a
--     re-import can never create a duplicate row (INSERT IGNORE).
--   * the Cloudinary image is stored in TWO columns:
--       imageUrl      → permanent Cloudinary `secure_url`
--       imagePublicId → Cloudinary `public_id` (replace/delete)
--   * timestamps/`date`/`publishedAt` are ISO-8601 strings, exactly
--     as the JSON documents carry them: the rows round-trip
--     byte-for-byte and no timezone conversion is introduced.
--     (Sorting is done in the API via `new Date(value)`.)
--   * `status` is 'published' | 'draft'; the public API only ever
--     returns published rows.
-- ============================================================

CREATE TABLE IF NOT EXISTS `news` (
  `id` VARCHAR(40) NOT NULL,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `shortDesc` VARCHAR(1000) NOT NULL DEFAULT '',
  `fullContent` MEDIUMTEXT NOT NULL,
  `imageUrl` VARCHAR(1000) NOT NULL DEFAULT '',
  `imagePublicId` VARCHAR(300) NOT NULL DEFAULT '',
  `date` VARCHAR(20) NOT NULL DEFAULT '',
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  `publishedAt` VARCHAR(40) NOT NULL DEFAULT '',
  `createdAt` VARCHAR(40) NOT NULL DEFAULT '',
  `updatedAt` VARCHAR(40) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_news_status` (`status`),
  KEY `idx_news_date` (`date`),
  KEY `idx_news_created_at` (`createdAt`),
  KEY `idx_news_status_date` (`status`, `date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
