/* Portfolio, careers, blog, privacy/terms, misc */
export const RAW = `
Digital Marketing Portfolio~Digital-Marketing-Portfolio~Portfolio de marketing digital~Portfolio di digital marketing~Portfolio de marketing digital~Portafolio de marketing digital
At Bluconnet Media Services, we believe every brand has a unique story that deserves to be told with clarity, creativity, and impact. Our digital marketing portfolio showcases a comprehensive suite of solutions designed to help businesses grow, engage audiences, and maximize online presence through strategic, result-driven implementation.~Bei Bluconnet Media Services glauben wir, dass jede Marke eine einzigartige Geschichte hat, die mit Klarheit, Kreativität und Wirkung erzählt werden sollte. Unser Digital-Marketing-Portfolio zeigt eine umfassende Palette an Lösungen, die Unternehmen helfen, zu wachsen, Zielgruppen zu binden und ihre Online-Präsenz durch strategische, ergebnisorientierte Umsetzung zu maximieren.~Chez Bluconnet Media Services, nous croyons que chaque marque a une histoire unique qui mérite d'être racontée avec clarté, créativité et impact. Notre portfolio de marketing digital présente une gamme complète de solutions conçues pour aider les entreprises à croître, engager les audiences et maximiser leur présence en ligne grâce à une mise en œuvre stratégique et orientée résultats.~Presso Bluconnet Media Services crediamo che ogni brand abbia una storia unica che merita di essere raccontata con chiarezza, creatività e impatto. Il nostro portfolio di digital marketing mostra una gamma completa di soluzioni pensate per aiutare le aziende a crescere, coinvolgere le audience e massimizzare la presenza online attraverso un'implementazione strategica orientata ai risultati.~Na Bluconnet Media Services acreditamos que toda marca tem uma história única que merece ser contada com clareza, criatividade e impacto. Nosso portfolio de marketing digital apresenta uma gama completa de soluções criadas para ajudar empresas a crescer, engajar audiências e maximizar a presença online através de una implementação estratégica orientada a resultados.~En Bluconnet Media Services creemos que cada marca tiene una historia única que merece ser contada con claridad, creatividad e impacto. Nuestro portafolio de marketing digital presenta una gama completa de soluciones diseñadas para ayudar a las empresas a crecer, fidelizar audiencias y maximizar su presencia online mediante una implementación estratégica orientada a resultados.
From start-ups finding their voices to established brands scaling new heights, our work highlights creativity, strategic thinking, and real business impact.~Von Start-ups, die ihre Stimme finden, bis zu etablierten Marken, die neue Höhen erreichen — unsere Arbeit zeigt Kreativität, strategisches Denken und echte geschäftliche Wirkung.~Des start-ups qui trouvent leur voix aux marques établies qui atteignent de nouveaux sommets, notre travail met en avant la créativité, la pensée stratégique et un réel impact commercial.~Dalle startup che trovano la propria voce ai brand affermati che raggiungono nuovi traguardi, il nostro lavoro mette in luce creatività, pensiero strategico e reale impatto sul business.~De startups que encontram sua voz a marcas estabelecidas que alcançam novos horizontes, nosso trabalho destaca criatividade, pensamento estratégico e impacto real nos negocios.~Desde startups que encuentran su voz hasta marcas establecidas que alcanzan nuevas cotas, nuestro trabajo destaca la creatividad, el pensamiento estratégico y el impacto real en el negocio.
Portfolio~Portfolio~Portfolio~Portfolio~Portfólio~Portafolio
PORTFOLIO~PORTFOLIO~PORTFOLIO~PORTFOLIO~PORTFÓLIO~PORTAFOLIO
VIEW ALL CASE STUDIES~ALLE FALLSTUDIEN ANZEIGEN~VOIR TOUTES LES ÉTUDES DE CAS~VEDI TUTTI I CASE STUDY~VER TODOS LOS ESTUDIOS DE CASO~VER TODOS LOS CASOS DE ÉXITO
VIEW CASE STUDY~FALLSTUDIE ANZEIGEN~VOIR L'ÉTUDE DE CAS~VEDI CASE STUDY~VER ESTUDIO DE CASO~VER CASO DE ÉXITO
SEE REAL OUTCOMES~ECHTE ERGEBNISSE SEHEN~VOIR LES RÉSULTATS RÉELS~VEDI I RISULTATI REALI~VEJA RESULTADOS REALES~VER RESULTADOS REALES
REAL OUTCOMES~ECHTE ERGEBNISSE~RÉSULTATS RÉELS~RISULTATI REALI~RESULTADOS REALES~RESULTADOS REALES
About Company?~Über das Unternehmen?~À propos de l'entreprise ?~Informazioni sull'azienda?~Sobre a empresa?~¿Sobre la empresa?
Add your image to~Fügen Sie Ihr Bild hinzu~Ajoutez votre image à~Aggiungi la tua immagine a~Adicione sua imagem a~Añade tu imagen a
More Than Just~Mehr als nur~Plus qu'une simple~Più di un semplice~Más que apenas~Más que solo
Something Amazing~Etwas Erstaunliches~Quelque chose d'incroyable~Qualcosa di straordinario~Algo incalcolável~Algo increíble
THROUGH~DURCH~GRÂCE~ATTRAVERSO~ATRAVÉS~A TRAVÉS
WITH BLUCONNETMEDIA~MIT BLUCONNETMEDIA~AVEC BLUCONNETMEDIA~CON BLUCONNETMEDIA~COM BLUCONNETMEDIA~CON BLUCONNETMEDIA
Discover how we've transformed brands and delivered exceptional results. From innovative campaigns to strategic digital solutions, see the work that has earned us industry recognition.~Entdecken Sie, wie wir Marken transformiert und herausragende Ergebnisse erzielt haben. Von innovativen Kampagnen bis zu strategischen digitalen Lösungen — sehen Sie die Arbeit, die uns Branchenanerkennung eingebracht hat.~Découvrez comment nous avons transformé des marques et obtenu des résultats exceptionnels. Des campagnes innovantes aux solutions numériques stratégiques, découvrez le travail qui nous a valu la reconnaissance du secteur.~Scopri come abbiamo trasformato i brand e ottenuto risultati eccezionali. Dalle campagne innovative alle soluzioni digitali strategiche, guarda il lavoro che ci ha fatto guadagnare il riconoscimento del settore.~Descubra como transformamos marcas e entregamos resultados excepcionales. Das campagnes inovadoras às soluções digitais estratégicas, veja o trabalho que nos valió o reconocimiento do sector.~Descubre cómo hemos transformado marcas y entregado resultados excepcionales. Desde campañas innovadoras hasta soluciones digitales estratégicas, mira el trabajo que nos ha valido el reconocimiento del sector.
`;
