/* About, portfolio, tech partners, guide, stats */
export const RAW = `
At BluConnet Media, we are a passionate team of digital innovators, creative thinkers, and strategic experts dedicated to transforming your brand's digital presence. We combine cutting-edge technology with creative excellence to deliver measurable results.~Bei BluConnet Media sind wir ein leidenschaftliches Team aus digitalen Innovatoren, kreativen Denkern und strategischen Experten, das sich der Transformation der digitalen Präsenz Ihrer Marke verschrieben hat. Wir verbinden modernste Technologie mit kreativer Exzellenz, um messbare Ergebnisse zu liefern.~Chez BluConnet Media, nous sommes une équipe passionnée d'innovateurs numériques, de penseurs créatifs et d'experts stratégiques dédiée à la transformation de la présence numérique de votre marque. Nous allions technologie de pointe et excellence créative pour produire des résultats mesurables.~In BluConnet Media siamo un team appassionato di innovatori digitali, menti creative ed esperti strategici dedicati a trasformare la presenza digitale del tuo brand. Combiniamo tecnologia all'avanguardia con eccellenza creativa per offrire risultati misurabili.~Na BluConnet Media, somos uma equipe apaixonada de inovadores digitais, pensadores criativos e experts estratégicos dedicados a transformar a presença digital da sua marca. Combinamos tecnologia de ponta com excelência criativa para entregar resultados mensurables.~En BluConnet Media, somos un equipo apasionado de innovadores digitales, pensadores creativos y expertos estratégicos dedicados a transformar la presencia digital de tu marca. Combinamos tecnología de vanguardia con excelencia creativa para ofrecer resultados medibles.
Our talented team of digital innovators, creative thinkers, and strategic experts are dedicated to transforming your brand's digital presence.~Unser talentiertes Team aus digitalen Innovatoren, kreativen Denkern und strategischen Experten ist der Transformation der digitalen Präsenz Ihrer Marke verpflichtet.~Notre équipe talentueuse d'innovateurs numériques, de penseurs créatifs et d'experts stratégiques est dédiée à la transformation de la présence numérique de votre marque.~Il nostro talentuoso team di innovatori digitali, menti creative ed esperti strategici è dedicato a trasformare la presenza digitale del tuo brand.~Nossa talentosa equipe de inovadores digitais, pensadores criativos e experts estratégicos está dedicada a transformar a presença digital da sua marca.~Nuestro talentoso equipo de innovadores digitales, pensadores creativos y expertos estratégicos está dedicado a transformar la presencia digital de tu marca.
30+ Global Awards~30+ globale Auszeichnungen~30+ récompenses mondiales~30+ premi globali~30+ prêmios globais~30+ premios globales
Est. 2018~Gegr. 2018~Depuis 2018~Dal 2018~Est. 2018~Est. 2018
EST. 2018 • DIGITAL AGENCY~EST. 2018 • DIGITAL-AGENTUR~DEPUIS 2018 • AGENCE DIGITALE~DAL 2018 • AGENZIA DIGITALE~EST. 2018 • AGÊNCIA DIGITAL~EST. 2018 • AGENCIA DIGITAL
ABOUT US • DIGITAL AGENCY • EST. 2018 ~ÜBER UNS • DIGITAL-AGENTUR • EST. 2018~À PROPOS • AGENCE DIGITALE • DEPUIS 2018~CHI SIAMO • AGENZIA DIGITALE • DAL 2018~SOBRE NOSOTROS • AGENCIA DIGITAL • EST. 2018~SOBRE NOSOTROS • AGENCIA DIGITAL • EST. 2018
Acceleration Partners is the strategic guide top-tier brands trust to navigate an AI-accelerated, margin-pressured, and increasingly complex partnership marketing ecosystem. We unify affiliate, influencer, and emerging partnership models into a single data-driven growth engine, helping teams cut through complexity with clarity, structure, and trusted decision support.~Acceleration Partners ist der strategische Partner, dem führende Marken vertrauen, um sich im KI-beschleunigten, margendruckgetriebenen und zunehmend komplexen Ökosystem des Partnership-Marketings zurechtzufinden. Wir vereinen Affiliate-, Influencer- und neue Partnerschaftsmodelle zu einer datengetriebenen Wachstumsmaschine und helfen Teams, Komplexität mit Klarheit, Struktur und vertrauenswürdiger Entscheidungsunterstützung zu bewältigen.~Acceleration Partners est le guide stratégique de confiance des grandes marques pour naviguer dans un écosystème de marketing de partenariat accéléré par l'IA, sous pression sur les marges et de plus en plus complexe. Nous unifions l'affiliation, l'influence et les nouveaux modèles de partenariat en un moteur de croissance unique piloté par la donnée, aidant les équipes à traverser la complexité avec clarté, structure et aide à la décision fiable.~Acceleration Partners è la guida strategica di cui i brand top di gamma si fidano per orientarsi in un ecosistema di partnership marketing accelerato dall'IA, sotto pressione sui margini e sempre più complesso. Unifichiamo affiliate, influencer e nuovi modelli di partnership in un unico motore di crescita data-driven, aiutando i team a superare la complessità con chiarezza, struttura e supporto decisionale affidabile.~Acceleration Partners é o guía estratégico de confianza das mellores marcas para navegar nun ecosistema de marketing de parcerías acelerado por IA, con presión sobre as marxes e cada vez máis complexo. Unimos afiliados, influencers e novos modelos de parcería nun único motor de crecemento baseado en datos, axudando aos equipos a xestionar a complexidade con claridade, estrutura e apoio á decisión fiable.~Acceleration Partners es la guía estratégica en la que confían las mejores marcas para navegar por un ecosistema de marketing de alianzas acelerado por IA, con presión sobre los márgenes y cada vez más complejo. Unificamos afiliados, influencers y nuevos modelos de alianza en un único motor de crecimiento basado en datos, ayudando a los equipos a superar la complejidad con claridad, estructura y apoyo a la decisión fiable.
AFFILIATE & INFLUENCER~AFFILIATE & INFLUENCER~AFFILIATION & INFLUENCE~AFFILIATE E INFLUENCER~AFILIADOS E INFLUENCERS~AFILIADOS E INFLUENCERS
MARKETING SUCCESS~MARKETING-ERFOLG~SUCCÈS MARKETING~SUCCESSO MARKETING~SUCCESSO MARKETING~ÉXITO EN MARKETING
Acceleration Partners~Acceleration Partners~Acceleration Partners~Acceleration Partners~Acceleration Partners~Acceleration Partners
CHOOSE AP~CHOOSE AP~CHOISIR AP~Scegli AP~Scegli AP~Elige AP
GUIDED BY AP'S 2025 YEAR IN REVIEW~GEFÜHRT VON AP'S JAHRESRÜCKBLICK 2025~GUIDÉ PAR LA REVUE DE L'ANNÉE 2025 D'AP~GUIDATO DAL RAPPORTO 2025 DI AP~GUIADO POL BALANÇO 2025 DA AP~GUIADO POR EL ANÁLISIS 2025 DE AP
SMARTER AFFILIATE GROWTH~SMARTERES AFFILIATE-WACHSTUM~CROISSANCE D'AFFILIATION PLUS INTELLIGENTE~CRESCITA AFFILIATE PIÙ INTELLIGENTE~CRECIMIENTO DE AFILIADOS MÁS INTELIGENTE~CRECIMIENTO DE AFILIACIÓN MÁS INTELIGENTE
PARTNERSHIP MARKETING'S~DES PARTNERSHIP-MARKETINGS~DU MARKETING DE PARTENARIAT~DEL PARTNERSHIP MARKETING~DO MARKETING DE PARCERÍAS~DEL MARKETING DE ALIANZAS
GUIDE~LEITFADEN~GUIDE~GUIDA~GUÍA~GUÍA
POLICY~GRUNDSATZ~POLITIQUE~POLITICA~POLÍTICA~POLÍTICA
CONDITIONS~BEDINGUNGEN~CONDITIONS~CONDIZIONI~CONDICIONES~CONDICIONES
2026 EDITION~AUSGABE 2026~ÉDITION 2026~EDIZIONE 2026~EDICIÓN 2026~EDICIÓN 2026
2026 Partnership Marketing Guide~Partnership-Marketing-Leitfaden 2026~Guide du marketing de partenariat 2026~Guida al partnership marketing 2026~Guía de marketing de parcerías 2026~Guía de marketing de alianzas 2026
FOR 2026~FÜR 2026~POUR 2026~PER IL 2026~PARA 2026~PARA 2026
TECHNOLOGIES & PARTNERS~TECHNOLOGIEN & PARTNER~TECHNOLOGIES & PARTENAIRES~TECNOLOGIE E PARTNER~TECNOLÓGIAS E PARCEIROS~TECNOLÓGIAS Y SOCIOS
PROPRIETARY TECH~PROPRIETÄRE TECHNOLOGIE~TECHNOLOGIE PROPRIÉTAIRE~TECNOLOGIA PROPRIETARIA~TECNOLOGÍA PROPIA~TECNOLOGÍA PROPIA
PROPRIETARY TECHNOLOGY POWERING~PROPRIETÄRE TECHNOLOGIE, DIE~TECHNOLOGIE PROPRIÉTAIRE ALIMENTANT~LA TECNOLOGIA PROPRIETARIA CHE~TECNOLOGÍA PROPIA QUE IMPULSA~TECNOLOGÍA PROPIA QUE IMPULSA
POWERED BY PROPRIETARY INSIGHTS FROM APVISION™~BEREITGESTELLT DURCH PROPRIETÄRE EINBLICKE VON APVISION™~ALIMENTÉ PAR LES ANALYSES PROPRIÉTAIRES D'APVISION™~ALIMENTATO DA ANALISI PROPRIETARIE DI APVISION™~IMPULSADO POR INSIGHTS PROPIETARIOS DE APVISION™~IMPULSADO POR PERSPECTIVAS PROPIETARIAS DE APVISION™
APVision Dashboard~APVision-Dashboard~Tableau de bord APVision~Dashboard APVision~Painel APVision~Panel de APVision
APVision:~APVision:~APVision :~APVision:~APVision:~APVision:
`;
